name: "Checks the github action using itself"
on: [push,pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-cpan-modules
          with:
        # cpan cache files are stored in `~/.cpan/sources` on Linux/macOS
        path: ~/.cpan/sources
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Makefile.PL') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
      - name: Prepare for tests
        run: |
          sudo cpan MP3::Info XML::RSS URI
          perl Makefile.PL
          make
      - name: Perform tests
        run: make disttest
